- manifests/defaults.pp
- manifests/master.pp
- manifests/master/config.pp
- spec/classes/puppet_master_config_spec.rb
- templates/autosign.conf.erb
> setup basic autosigning.

- .travis.yml
Switching off HipChat notifications and adding Slack notifications
> testing slack integration

- manifests/master.pp
- manifests/master/install.pp
- spec/classes/puppet_master_install_spec.rb
Hello,
I rebased on your latest commit and added the spec tests as discussed. Let me know if this matches your expectations.
Best regards,
Thomas Equeter
> made hiera-eyaml package management optional

- manifests/setting.pp
- spec/defines/setting_spec.rb
> Adding a new define to add settings to puppet.conf

- README.md
- manifests/master.pp
- manifests/master/hiera.pp
- manifests/master/install.pp
- spec/classes/puppet_master_hiera_spec.rb
- spec/classes/puppet_master_install_spec.rb
- templates/hiera.yaml.erb
Hi,
PR for adding in support for hiera's merge_behaviour functionality.
http://docs.puppetlabs.com/hiera/latest/configuring.html#mergebehavior
> Added support for hiera merge_behavior

- README.md
- manifests/master.pp
- manifests/profile/master.pp
Hi @rendhalver Apologies, when I did #68 I forgot to add the new params into the master profile. This PR adds those.
> Add additional params to master profile

- CHANGELOG.md
- manifests/profile/r10k.pp
- templates/r10k.yaml.erb
Fix for r10k purgedirs error as that parameter is now deprecated in upstream module.
> Fix for r10k purgedirs error

- manifests/agent.pp
- spec/classes/puppet_agent_spec.rb
Fix for issue #66, with tests.
> Fix for issue #66, with tests.

- manifests/agent.pp
- spec/classes/puppet_agent_spec.rb
with option -t this will always generate emails to our dev ops centers in the world, so be quiet on sucess
> in cron mode, the agent should be quiet on sucess

- manifests/profile/master.pp
> #82 Fix puppetserver connect to non SSL puppetdb

- manifests/agent.pp
- spec/classes/puppet_agent_spec.rb
Sysconfig changes must be done before service start.
> define relationship between sysconfig and service

- manifests/profile/r10k.pp
Fixes abstractitptyltd/abstractit-puppet#90
> Fix r10k manage_ruby_dependency error

- manifests/profile/master.pp
Fixes abstractitptyltd/abstractit-puppet#97
> Fix could not find init script in some cases

- manifests/defaults.pp
- manifests/fact.pp
- manifests/facts.pp
- manifests/init.pp
- spec/classes/puppet_spec.rb
- spec/defines/fact_spec.rb
I'm helping out @aquister on this one. He started #114 to fix issue #87 but has gone AWOL after some changes were requested by @rendhalver. This PR includes the requested change (allow for backwards compatibility for Puppet 3).
Additionally, @aquister did something funny with his fork and github.com has no record of his branch (see "`unknown repository`" on #114?), and as such I was not able to submit a PR to his personal repo. So I started this new one. **When considering merging this PR please give priority to @aquister in #114, should he return.**
I'm a spec noob, can anyone please advise how they would like me to handle the spec tests? I only deleted them to have the git diff call attention to it. I am not suggesting to merge it as-is.
> Changed group owner for facter dirs to root - 2nd attempt

- .travis.yml
Add puppet gem support for version 4.10.1
> Add support for puppet 4.10.1

- metadata.json
> Change zack/r10k dependency to puppet/r10k

- Gemfile
- Gemfile.lock
- LICENSE-2.0.txt
> Add licence file.

- manifests/repo/apt.pp
- metadata.json
- spec/classes/puppet_repo_apt_spec.rb
Fix #152 
Updated the apt repo and the tests. Hopefully I did it correctly.
I tested the changes on my production environment and works perfectly.
> Fix to make module compatible with puppetlabs-apt 2.0.0

- manifests/config.pp
- manifests/init.pp
- manifests/profile/agent.pp
- spec/classes/puppet_config_spec.rb
I added and tested the missing config parameter `ca_port` following your way :)
> added ca_port for puppet agent configuration

- manifests/defaults.pp
- manifests/repo/yum.pp
- spec/classes/puppet_repo_yum_spec.rb
This key was generated when Puppet changed from 'puppetlabs' to 'puppet'
> Use the new puppet GPG key
